include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    sort_child_properties_last: true
    always_declare_return_types: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    # Đúng đắn khi làm việc async (quan trọng khi ghép API thật)
    unawaited_futures: true
    use_build_context_synchronously: true
    avoid_dynamic_calls: true
    # Gọn & nhất quán import giữa nhiều người
    directives_ordering: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
